Adding Permission Boundary option to IAM Role Creation
doitintl/terraform-eks-lens pull request #4
Opened 2024-05-22 14:44 UTC by gthomson31

#3  - This PR is to fix the missing permissions boundary

2024-05-30 13:21 UTC, eyalzek requested changes
Requested some formatting changes.

Could you also give an example of a value to be passed to this new variables? I'm not familiar with this feature.

2024-05-30 13:21 UTC, eyalzek commented on cluster/main.tf
> +
remove extra line

2024-05-30 13:21 UTC, eyalzek commented on cluster/main.tf
> +
remove extra line

2024-05-30 13:21 UTC, eyalzek commented on region-base/main.tf
> +
remove extra line

2024-06-03 14:38 UTC, gthomson31 commented
> Requested some formatting changes.
> 
> Could you also give an example of a value to be passed to this new variables? I'm not familiar with this feature.

WIll make the changes suggested - We use a permissions boundaries to set a limitation on the permissions any role or user can have.

Example would be passing an existing AWS policy ARN to be used as the boundary

By default any of our users must attach the permissions boundary to any created IAM Resource/.
This way we can have a more granilur control over what our users and roles have access to within our estate that couldnt be covered by SCP.

I have posted an example boundary policy below.

https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html

```

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "*",
            "Resource": "*",
            "Effect": "Allow",
            "Sid": "AllowAllAction"
        },
        {
            "Condition": {
                "StringNotEquals": {
                    "iam:PermissionsBoundary": "arn:aws:iam::123456789012:policy/ExampleBoundaryPolicy"
                }
            },
            "Action": [
                "iam:AttachRolePolicy",
                "iam:CreateRole",
                "iam:DeleteRolePolicy",
                "iam:DetachRolePolicy",
                "iam:PutRolePermissionsBoundary",
                "iam:AttachUserPolicy",
                "iam:CreateUser",
                "iam:DeleteUserPolicy",
                "iam:DetachUserPolicy",
                "iam:PutUserPermissionsBoundary"
            ],
            "Resource": "*",
            "Effect": "Deny",
            "Sid": "AllowCreationOfRolesWithOutBoundary"
        },
        {
            "Action": [
                "iam:*Put*",
                "iam:*Create*",
                "iam:*Delete*"
            ],
            "Resource": [
                "arn:aws:iam::123456789012:policy/ExampleBoundaryPolicy"
            ],
            "Effect": "Deny",
            "Sid": "DenyModificationBoundaryPolicy"
        },
        {
            "Action": [
                "iam:CreatePolicyVersion",
                "iam:DeletePolicy",
                "iam:DeletePolicyVersion",
                "iam:SetDefaultPolicyVersion"
            ],
            "Resource": [
                "arn:aws:iam::123456789012:policy/ExampleBoundaryPolicy"
            ],
            "Effect": "Deny",
            "Sid": "DenySpecificActionForBoundaryPolicy"
        }
    ]
}

2024-06-06 07:58 UTC, hobord requested changes

2024-06-06 07:58 UTC, hobord commented on cluster/main.tf
> +  permissions_boundary = var.permissions_boundary
align =

2024-06-06 07:58 UTC, hobord commented on region-base/main.tf
> +  permissions_boundary = var.permissions_boundary
align =

2024-07-23 07:06 UTC, merged