add otions to control to otel resources
doitintl/terraform-eks-lens pull request #5
Opened 2024-10-08 13:43 UTC by hobord

2024-10-08 13:58 UTC, eyalzek commented on cluster/variables.tf
> +  }
I'm confused about the mixing of colon and equal signs

2024-10-08 14:03 UTC, eyalzek commented
Did someone run into issues, or why is this change suggested?
Reading through [1] it sounds like this should be done on top of configuring `GOMEMLIMIT` and probably memory requests/limits since this is running on k8s.
But in this case the resource requirements are optional and the memory limiter has defaults set, so I'm slightly confused.

[1] https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiterprocessor/README.md#best-practices

2024-10-11 10:11 UTC, hobord commented
I added the option to set the GOMEMLIMIT env variable too...

2024-10-11 11:33 UTC, eyalzek requested changes
Update readme [1] to reflect new variables. Might also be useful to add a `description` rather than inline comments

[1] https://github.com/doitintl/terraform-eks-lens/blob/main/cluster/README.md

2024-10-11 14:02 UTC, eyalzek approved these changes

2024-10-15 07:24 UTC, lauraseidler approved these changes

2024-10-15 08:36 UTC, merged